#Handling Missing Values

In [3]:
import pandas as pd

# 1. import csv file

In [5]:
data = pd.read_csv('6_ex.csv')
print(data.head())

   SL no  Train no      Name of Trains   Off-day  Starting station   \
0      1        701    Subarna Express    Friday        Chittagong
1      2        702    Subarna Express    Friday                NaN
2      3        703   Mohanagar Goduli        NaN       Chittagong
3      4        704  Mohanagar Provati        NaN            Dhaka
4      5        705      Ekota Express   Tuesday             Dhaka

  Departure Time  Arrival Station Arrival time
0            7:00          Dhaka            NaN
1           15:00     Chittagong          20:30
2           15:00          Dhaka            NaN
3            7:45     Chittagong          14:55
4           10:00       Dinajpur          19:45

In [22]:
d = data.copy()
d = d.loc[:, ['Train no ', 'Name of Trains ', 'Starting station ', 'Off-day ', 'Arrival time ']]

print(d.head())

   Train no      Name of Trains  Starting station   Off-day  Arrival time
0        701    Subarna Express        Chittagong    Friday            NaN
1        702    Subarna Express                NaN   Friday          20:30
2        703   Mohanagar Goduli        Chittagong        NaN           NaN
3        704  Mohanagar Provati             Dhaka        NaN         14:55
4        705      Ekota Express             Dhaka   Tuesday          19:45

#2. Dropna

# 2.1 Drop by Row

In [14]:

d1 = data.copy()
d1 = d1.loc[:, ['Name of Trains ', 'Starting station ', 'Off-day ', 'Arrival time ']]
print(d1.head(7))
print()

d1.dropna(axis=0, inplace=True)
print(d1.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

     Name of Trains  Starting station     Off-day  Arrival time
4     Ekota Express             Dhaka     Tuesday          19:45
6     Tista Express             Dhaka      Monday          12:45
7     Tista Express         Dewangong      Monday          20:45
8   Parabat Express             Dhaka     Tuesday          13:40
9   Parabat Express            Sylhet     Tuesday          22:25
10   Upukol Express          Noakhali   Wednesday          12:30
11   Upukol Express             Dhaka     Tuesday          21:40

#2.2 Drop by Column

In [18]:
d2 = d.copy()
print(d2.head(7))
print()

d2.dropna(axis=1, inplace=True)
print(d2.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains
0    Subarna Express
1    Subarna Express
2   Mohanagar Goduli
3  Mohanagar Provati
4      Ekota Express
5      Ekota Express
6      Tista Express

# 2.3 How parameter

In [20]:
d3 = d.copy()
print(d3.head(7))
print()

d3.dropna(axis=0, how='all', inplace=True) #all vs any
print(d3.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

# 2.4 Subset

```
# Delete None data by specific column
```

In [22]:
d4 = d.copy()
print(d4.head(7))
print()

d4.dropna(axis=0, subset=['Off-day '], inplace=True)
print(d4.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

    Name of Trains  Starting station   Off-day  Arrival time
0  Subarna Express        Chittagong    Friday            NaN
1  Subarna Express                NaN   Friday          20:30
4    Ekota Express             Dhaka   Tuesday          19:45
5    Ekota Express                NaN   Monday           7:10
6    Tista Express             Dhaka    Monday          12:45
7    Tista Express         Dewangong    Monday          20:45
8  Parabat Express             Dhaka   Tuesday          13:40

# 2.5 thresh parameter



```
# thresh=n, here if any row contain n number of NULL value then it will be remove
```

In [29]:
d5 = d.copy()
print(d5.head(7))
print()

d5.dropna(thresh=3, inplace=True)
print(d5.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45
7      Tista Express         Dewangong    Monday          20:45

# 3. Fillna

# 3.1 Fill all entity

In [9]:
d6 = d.copy()
print(d6.head(7))
print()

d6.fillna(7.17, inplace=True)
print(d6.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday           7.17
1    Subarna Express               7.17   Friday          20:30
2   Mohanagar Goduli        Chittagong       7.17          7.17
3  Mohanagar Provati             Dhaka       7.17         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express               7.17   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

  # 3.2 Fill with specific column

In [13]:
d7 = d.copy()
print(d7.head(7))
print()

# d7['Arrival time '].fillna(7.17, inplace=True)
d7 = d7.fillna({'Starting station ' : 'Dhaka ', 'Off-day ' : 'Friday ', 'Arrival time ' : '20:45'})
print(d7.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday          20:45
1    Subarna Express             Dhaka    Friday          20:30
2   Mohanagar Goduli        Chittagong    Friday          20:45
3  Mohanagar Provati             Dhaka    Friday          14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express             Dhaka    Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

# 3.3 Fill with forward and backword field


```
# 1. Forward row
# 2. Backword row
# 3. Forward column
# 4. Backword Column
```

In [14]:
d8 = d.copy()
print(d8.head(7))
print()

d8.fillna(method='ffill', inplace=True)
print(d8.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express        Chittagong    Friday          20:30
2   Mohanagar Goduli        Chittagong    Friday          20:30
3  Mohanagar Provati             Dhaka    Friday          14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express             Dhaka    Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

<ipython-input-14-6982b36ea3f7>:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  d8.fillna(method='ffill', inplace=True)

In [15]:
d9 = d.copy()
print(d9.head(7))
print()

d9.fillna(method='bfill', inplace=True)
print(d9.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday          20:30
1    Subarna Express        Chittagong    Friday          20:30
2   Mohanagar Goduli        Chittagong   Tuesday          14:55
3  Mohanagar Provati             Dhaka   Tuesday          14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express             Dhaka    Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

<ipython-input-15-160a5c1a02b1>:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  d9.fillna(method='bfill', inplace=True)

In [16]:
d10 = d.copy()
print(d10.head(7))
print()

d10.fillna(method='ffill', axis=1, inplace=True)
print(d10.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains  Starting station      Off-day  Arrival time
0    Subarna Express        Chittagong       Friday        Friday
1    Subarna Express   Subarna Express       Friday          20:30
2   Mohanagar Goduli        Chittagong   Chittagong    Chittagong
3  Mohanagar Provati             Dhaka        Dhaka          14:55
4      Ekota Express             Dhaka      Tuesday          19:45
5      Ekota Express     Ekota Express       Monday           7:10
6      Tista Express             Dhaka       Monday          12:45

<ipython-input-16-e5a88ea556fd>:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  d10.fillna(method='ffill', axis=1, inplace=True)

In [17]:
d11 = d.copy()
print(d11.head(7))
print()

d11.fillna(method='bfill', axis=1, inplace=True)
print(d11.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express            Friday    Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka      14:55         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express            Monday    Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

<ipython-input-17-005460784115>:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  d11.fillna(method='bfill', axis=1, inplace=True)

# 3.4 Limit method


```
# When i should fill limited data of a row, then use it
```

In [20]:
d12 = d.copy()
print(d12.head(7))
print()

d12.fillna('ABCD', limit=1, inplace=True)
print(d12.head(7))

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday            NaN
1    Subarna Express                NaN   Friday          20:30
2   Mohanagar Goduli        Chittagong        NaN           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

      Name of Trains  Starting station   Off-day  Arrival time
0    Subarna Express        Chittagong    Friday           ABCD
1    Subarna Express               ABCD   Friday          20:30
2   Mohanagar Goduli        Chittagong       ABCD           NaN
3  Mohanagar Provati             Dhaka        NaN         14:55
4      Ekota Express             Dhaka   Tuesday          19:45
5      Ekota Express                NaN   Monday           7:10
6      Tista Express             Dhaka    Monday          12:45

# 4. Replace

#4.1 replace_to 7 to 9

In [33]:
d13 = d.copy()
print(d13.head(7))
print()

d13.replace(to_replace='Dhaka ' , value='Rajshahi', inplace=True)
print(d13.head(7))

   Train no      Name of Trains  Starting station   Off-day  Arrival time
0        701    Subarna Express        Chittagong    Friday            NaN
1        702    Subarna Express                NaN   Friday          20:30
2        703   Mohanagar Goduli        Chittagong        NaN           NaN
3        704  Mohanagar Provati             Dhaka        NaN         14:55
4        705      Ekota Express             Dhaka   Tuesday          19:45
5        706      Ekota Express                NaN   Monday           7:10
6        707      Tista Express             Dhaka    Monday          12:45

   Train no      Name of Trains  Starting station   Off-day  Arrival time
0        701    Subarna Express        Chittagong    Friday            NaN
1        702    Subarna Express                NaN   Friday          20:30
2        703   Mohanagar Goduli        Chittagong        NaN           NaN
3        704  Mohanagar Provati           Rajshahi       NaN         14:55
4        705      Ekota Express           Rajshahi  Tuesday          19:45
5        706      Ekota Express                NaN   Monday           7:10
6        707      Tista Express           Rajshahi   Monday          12:45

# 4.2 replace using dictorionary

In [34]:
d14 = d.copy()
print(d14.head(7))
print()

d14.replace(to_replace={'Dhaka ' : 'Rajshahi', 'Friday ' : 'Saturday'}, inplace=True)
print(d14.head(7))

   Train no      Name of Trains  Starting station   Off-day  Arrival time
0        701    Subarna Express        Chittagong    Friday            NaN
1        702    Subarna Express                NaN   Friday          20:30
2        703   Mohanagar Goduli        Chittagong        NaN           NaN
3        704  Mohanagar Provati             Dhaka        NaN         14:55
4        705      Ekota Express             Dhaka   Tuesday          19:45
5        706      Ekota Express                NaN   Monday           7:10
6        707      Tista Express             Dhaka    Monday          12:45

   Train no      Name of Trains  Starting station   Off-day  Arrival time
0        701    Subarna Express        Chittagong   Saturday           NaN
1        702    Subarna Express                NaN  Saturday         20:30
2        703   Mohanagar Goduli        Chittagong        NaN           NaN
3        704  Mohanagar Provati           Rajshahi       NaN         14:55
4        705      Ekota Express           Rajshahi  Tuesday          19:45
5        706      Ekota Express                NaN   Monday           7:10
6        707      Tista Express           Rajshahi   Monday          12:45

# 4.3 Regex

In [35]:
d15 = d.copy()
print(d15.head(7))
print()

d15.replace(to_replace='[A-Za-z]', value='0', regex=True, inplace=True)
print(d15.head(7))

   Train no      Name of Trains  Starting station   Off-day  Arrival time
0        701    Subarna Express        Chittagong    Friday            NaN
1        702    Subarna Express                NaN   Friday          20:30
2        703   Mohanagar Goduli        Chittagong        NaN           NaN
3        704  Mohanagar Provati             Dhaka        NaN         14:55
4        705      Ekota Express             Dhaka   Tuesday          19:45
5        706      Ekota Express                NaN   Monday           7:10
6        707      Tista Express             Dhaka    Monday          12:45

   Train no      Name of Trains  Starting station   Off-day  Arrival time
0        701    0000000 0000000        0000000000    000000            NaN
1        702    0000000 0000000                NaN   000000          20:30
2        703   000000000 000000        0000000000        NaN           NaN
3        704  000000000 0000000             00000        NaN         14:55
4        705      00000 0000000             00000   0000000          19:45
5        706      00000 0000000                NaN   000000           7:10
6        707      00000 0000000             00000    000000          12:45

# 4.4 method, limit, inplace same as fillna

In [48]:
d16 = d.copy()
print(d16.head(7))
print()

d16.replace('Friday ', method='ffill', limit=1, inplace=True)
print(d16.head(7))

   Train no      Name of Trains  Starting station   Off-day  Arrival time
0        701    Subarna Express        Chittagong    Friday            NaN
1        702    Subarna Express                NaN   Friday          20:30
2        703   Mohanagar Goduli        Chittagong        NaN           NaN
3        704  Mohanagar Provati             Dhaka        NaN         14:55
4        705      Ekota Express             Dhaka   Tuesday          19:45
5        706      Ekota Express                NaN   Monday           7:10
6        707      Tista Express             Dhaka    Monday          12:45

   Train no      Name of Trains  Starting station   Off-day  Arrival time
0        701    Subarna Express        Chittagong    Friday            NaN
1        702    Subarna Express                NaN   Friday          20:30
2        703   Mohanagar Goduli        Chittagong        NaN           NaN
3        704  Mohanagar Provati             Dhaka        NaN         14:55
4        705      Ekota Express             Dhaka   Tuesday          19:45
5        706      Ekota Express                NaN   Monday           7:10
6        707      Tista Express             Dhaka    Monday          12:45

<ipython-input-48-3ad527263dc2>:5: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  d16.replace('Friday ', method='ffill', limit=1, inplace=True)

#5. Interpolate


```
# interpolate works with only numarical data
# It has many method. try to search it in google
```

# 5.1 Noraml Interpolate

In [54]:
dx = pd.read_csv('student_data.csv')
d17 = dx.copy()
print(d17.head(7))
print()

d17.interpolate(method='linear', inplace=True)
print(d17.head(7))

    ID           Name   Age  CGPA              Address
0  1.0  Alice Johnson  21.0   3.8     123 Maple Street
1  NaN      Bob Smith  22.0   3.2       456 Oak Avenue
2  3.0  Charlie Brown   NaN   NaN        789 Pine Road
3  NaN   Diana Prince  23.0   NaN       321 Birch Lane
4  5.0    Evan Wright   NaN   3.4  654 Cedar Boulevard
5  6.0    Fiona Davis  22.0   NaN   987 Spruce Terrace
6  7.0   George Clark   NaN   3.1   159 Redwood Circle

    ID           Name   Age      CGPA              Address
0  1.0  Alice Johnson  21.0  3.800000     123 Maple Street
1  2.0      Bob Smith  22.0  3.200000       456 Oak Avenue
2  3.0  Charlie Brown  22.5  3.266667        789 Pine Road
3  4.0   Diana Prince  23.0  3.333333       321 Birch Lane
4  5.0    Evan Wright  22.5  3.400000  654 Cedar Boulevard
5  6.0    Fiona Davis  22.0  3.250000   987 Spruce Terrace
6  7.0   George Clark  22.5  3.100000   159 Redwood Circle

<ipython-input-54-cb026468359a>:6: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  d17.interpolate(method='linear', inplace=True)

# 5.2 limit-Direction


```
# backword
# forward
#both
```

In [55]:
d18 = dx.copy()
print(d18.head(7))
print()

d18.interpolate(method='linear', limit=1, limit_direction='backward', inplace=True)
print(d18.head(7))

    ID           Name   Age  CGPA              Address
0  1.0  Alice Johnson  21.0   3.8     123 Maple Street
1  NaN      Bob Smith  22.0   3.2       456 Oak Avenue
2  3.0  Charlie Brown   NaN   NaN        789 Pine Road
3  NaN   Diana Prince  23.0   NaN       321 Birch Lane
4  5.0    Evan Wright   NaN   3.4  654 Cedar Boulevard
5  6.0    Fiona Davis  22.0   NaN   987 Spruce Terrace
6  7.0   George Clark   NaN   3.1   159 Redwood Circle

    ID           Name   Age      CGPA              Address
0  1.0  Alice Johnson  21.0  3.800000     123 Maple Street
1  2.0      Bob Smith  22.0  3.200000       456 Oak Avenue
2  3.0  Charlie Brown  22.5       NaN        789 Pine Road
3  4.0   Diana Prince  23.0  3.333333       321 Birch Lane
4  5.0    Evan Wright  22.5  3.400000  654 Cedar Boulevard
5  6.0    Fiona Davis  22.0  3.250000   987 Spruce Terrace
6  7.0   George Clark  22.5  3.100000   159 Redwood Circle

<ipython-input-55-41ee51084e69>:5: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  d18.interpolate(method='linear', limit=1, limit_direction='backward', inplace=True)

# 5.3 Limit area


```
inside
outside
```

In [57]:
d19 = dx.copy()
print(d19.head(7))
print()

d19.interpolate(limit_area='outside', inplace=True)
print(d19.head(7))

    ID           Name   Age  CGPA              Address
0  1.0  Alice Johnson  21.0   3.8     123 Maple Street
1  NaN      Bob Smith  22.0   3.2       456 Oak Avenue
2  3.0  Charlie Brown   NaN   NaN        789 Pine Road
3  NaN   Diana Prince  23.0   NaN       321 Birch Lane
4  5.0    Evan Wright   NaN   3.4  654 Cedar Boulevard
5  6.0    Fiona Davis  22.0   NaN   987 Spruce Terrace
6  7.0   George Clark   NaN   3.1   159 Redwood Circle

    ID           Name   Age  CGPA              Address
0  1.0  Alice Johnson  21.0   3.8     123 Maple Street
1  NaN      Bob Smith  22.0   3.2       456 Oak Avenue
2  3.0  Charlie Brown   NaN   NaN        789 Pine Road
3  NaN   Diana Prince  23.0   NaN       321 Birch Lane
4  5.0    Evan Wright   NaN   3.4  654 Cedar Boulevard
5  6.0    Fiona Davis  22.0   NaN   987 Spruce Terrace
6  7.0   George Clark   NaN   3.1   159 Redwood Circle

<ipython-input-57-05fa07b40aa6>:5: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  d19.interpolate(limit_area='outside', inplace=True)